exclude: 'node_modules'
repos:
- repo: https://github.com/pre-commit/mirrors-eslint
  sha: v3.18.0
  hooks:
  - id: eslint
    name: Check for JavaScript style violations
    files: '.*.js$'
    additional_dependencies:
      - babel-eslint@8.2.6
      - eslint@5.1.0
    args:
      - --config=./.eslintrc.json
      - --fix
      - --color
      - --quiet
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.1-1
  hooks:
    - id: pretty-format-json
      name: Pretty format JSON
      args:
        - --no-sort-keys

    - id: trailing-whitespace
      name: Fix trailing whitespace

    - id: end-of-file-fixer
      name: Fix missing EOF

    - id: check-executables-have-shebangs
      name: Check exeutables for shebangs

    - id: check-added-large-files
      name: Check for any large files added

    - id: check-merge-conflict
      name: Check for merge conflict fragments

    - id: check-case-conflict
      name: Check for filesystem character case conflicts

    - id: detect-private-key
      name: Check for cleartext private keys stored

    - id: flake8
      name: Check for Python style guideline violations
      files: '^(server)/.*\.py'

    - id: check-yaml
      exclude: 'ansible/.*/templates/.*.ya?ml'
      name: Validate YAML

    - id: check-json
      name: Validate JSON

    - id: check-ast
      files: '^(server)/.*\.py'
      name: Check Python abstract syntax tree

    - id: double-quote-string-fixer
      files: '^(server)/.*\.py'
      name: Replace Python " with '

    - id: autopep8-wrapper
      args:
        - --in-place
        - --aggressive
        - --aggressive
        - --experimental
      files: '^(server)/.*\.py'
      name: Pretty format Python

- repo: https://github.com/asottile/reorder_python_imports
  sha: v1.1.1
  hooks:
    - id: reorder-python-imports
      name: Reorder Python imports
      files: '^(server)/.*\.py'

- repo: https://github.com/asottile/add-trailing-comma
  sha: v0.7.0
  hooks:
    - id: add-trailing-comma
      name: Fix Python trailing commas
      args:
        - --py36-plus
      files: '^(server)/.*\.py'
