---
# file: site.yml

- hosts: nickficano.com
  become: yes
  gather_facts: False

  pre_tasks:
    - name: install python2
      raw: sudo bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qy python-minimal)"

    - name: install aptitude
      raw: sudo apt-get -y install aptitude

  roles:
    - common
    - ntp
    - nginx
    - supervisord
    - nickficano.com
    - letsencrypt
    - dhparam
