---
  - name: install ntp daemon
    apt: pkg=ntp state=present

  - name: ensure ntp daemon autostart
    service: name=ntp enabled=yes

  - name: setup ntp config
    template: src=templates/ntp.conf dest=/etc/ntp.conf
    notify: Restart NTP daemon
