- name: NGINX | adding nginx signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

- name: NGINX | adding sources.list deb url for nginx
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"

- name: NGINX | updating apt cache
  apt:
    update_cache: yes

- name: NGINX | install
  apt:
    pkg: nginx
    state: latest

- name: NGINX | remove default site
  action: file path=/etc/nginx/conf.d/default.conf state=absent

- name: nginx config
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
  become: yes
  notify:
    - reload nginx

- name: NGINX | starting nginx
  service:
    name: nginx
    state: started
