---

- name: install openssl
  apt:
    name: openssl
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - dhparam

- name: create output directory for dhparam
  file:
    path: "{{ dhparam_file | dirname }}"
    state: directory
  become: yes
  tags:
    - dhparam

- name: generate diffie-hellman parameter file
  command: "{{ dhparam_openssl_binary }} dhparam -out '{{ dhparam_file }}' {{ dhparam_size }}"
  args:
    creates: "{{ dhparam_file }}"
  become: yes
  tags:
    - dhparam

- include: cron.yml
