---
# file: host_vars/nickficano.com.yml

app:
  name: nickficano.com
  repo_url: https://github.com/nficano/nickficano.com.git
  user: app
  group: apps
  process_name: nf_www
  deploy_user: ubuntu

letsencrypt_email: nficano@gmail.com
letsencrypt_renewal_enabled: true
letsencrypt_webroot_path: /var/www/html
letsencrypt_cert_domains:
  - nickficano.com
  - www.nickficano.com

dhparam_size: 4096
dhparam_file: /etc/ssl/certs/dhparam-{{ dhparam_size }}.pem
dhparam_update_enabled: true
dhparam_update_interval: weekly
dhparam_openssl_binary: openssl
