---
# file: roles/nginx/tasks/main.yml

- name: adding nginx signing key
  apt_key:
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: update apt cache
  apt:
    update_cache: yes

- name: install
  apt:
    pkg: nginx
    state: latest

- name: remove default site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: write nginx configuration
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf
  become: yes
  notify:
    - reload nginx

- name: create nginx snippets directory
  file:
    path: /etc/nginx/snippets
    state: directory
    follow: yes
  become: yes

- name: start nginx
  service:
    name: nginx
    state: started
