---
# file: roles/letsencrypt/defaults/main.yml

letsencrypt_src_directory: /usr/local/share/letsencrypt
letsencrypt_venv: "{{ letsencrypt_src_directory }}/env"
letsencrypt_cert_domains:
  - "{{ ansible_fqdn }}"
letsencrypt_webroot_path: /var/www
letsencrypt_authenticator: webroot
letsencrypt_email: "webmaster@{{ ansible_domain }}"
letsencrypt_command: "{{ letsencrypt_venv }}/bin/letsencrypt -n --agree-tos  {% if letsencrypt_rsa_key_size is defined %}--rsa-key-size {{ letsencrypt_rsa_key_size }}{% endif %} --text {% for domain in letsencrypt_cert_domains %}-d {{ domain }} {% endfor %}--email {{ letsencrypt_email }} {% if letsencrypt_server is defined %}--server {{ letsencrypt_server }}{% endif %} --expand"

letsencrypt_renewal_frequency: daily
letsencrypt_renewal_enabled: no

letsencrypt_pkp_hashes:
  - G5Yh5Mo/24pSh64SB3fhj0L5FZpnp4xjEg/INNDt9t8= # templates/backup.key.pem
  - TRi1sP2dt38aFrLNgr+zmllBN3tlzm0B/Hb4JZxrGvk= # templates/backup2.key.pem
  - YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg= # Let's Encrypt Authority X3
  - sRHdihwgkaib1P1gxX8HFszlD+7/gTfNvuAybgLPNis= # Let's Encrypt Authority X4
  - C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M= # ISRG Root X1
  - Vjs8r4z+80wjNcr1YKepWQboSIRi63WsWXhIMN+eWys= # DST Root CA X3
