---
# file: roles/users/tasks/main.yml

- name: upsert groups
  group:
    name: "{{ app.group }}"
    state: present

- name: upsert users
  user:
    name: "{{ app.user }}"
    group: "{{ app.group }}"
    createhome: yes

- name: add .ssh folder
  file:
    path: /home/{{ app.user }}/.ssh
    owner: "{{ app.user }}"
    group: "{{ app.group }}"
    state: directory
    mode: 0700
