---
# file: roles/nickficano.com/tasks/main.yml

- name: install python build packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - build-essential
    - libffi-dev
    - libssl-dev
    - python-dev
    - python-setuptools

- name: install pip
  easy_install:
    name: pip

- name: install pipenv
  pip:
    name: pipenv
  tags:
    - deploy

- name: install virtualenv
  pip:
    name: virtualenv
    virtualenv_python: python3.6
  tags:
    - deploy

- name: pull latest app updates from github
  become: yes
  become_user: "{{ app.user }}"
  git:
    repo: "{{ app.repo_url }}"
    dest: /home/{{ app.user }}/{{ app.name }}
    accept_hostkey: yes
    force: yes
  tags:
    - deploy

- name: setup pipenv
  become: yes
  become_user: "{{ app.user }}"
  command: pipenv install --ignore-pipfile
  args:
    chdir: /home/{{ app.user }}/{{ app.name }}
  tags:
    - deploy

- name: create .virtualenvs directory
  become: yes
  file:
    owner: "{{ app.user }}"
    group: "{{ app.group }}"
    path: /home/{{ app.user }}/.virtualenvs
    state: directory
    mode: 0755
  tags:
    - deploy

- name: get path to pipenv virtualenv
  become: yes
  become_user: "{{ app.user }}"
  shell: pipenv --venv
  args:
    chdir: /home/{{ app.user }}/{{ app.name }}
  register: virtualenv_path
  tags:
    - deploy

- name: create symlink to pipenv virtualenv
  become: yes
  become_user: "{{ app.user }}"
  file:
    src: "{{ virtualenv_path.stdout }}"
    dest: /home/{{ app.user }}/.virtualenvs/{{ app.name }}.pipenv
    state: link
  tags:
    - deploy

- name: install node.js project dependancies
  become: yes
  become_user: app
  command: yarn install
  args:
    chdir: /home/{{ app.user }}/{{ app.name }}
  tags:
    - deploy

- name: bundle static assets
  become: yes
  become_user: app
  command: yarn run bundle
  args:
    chdir: /home/{{ app.user }}/{{ app.name }}
  tags:
    - deploy

- name: create directory for letsencrypt auto renewal verification
  file:
    path: /var/www/html/.well-known/acme-challenge
    state: directory
    mode: 0755

- name: create directory for uwsgi process configuration
  file:
    path: /etc/uwsgi
    state: directory
    mode: 0755

- name: create directory for uwsgi log
  file:
    owner: "{{ app.user }}"
    group: "{{ app.group }}"
    path: /var/log/uwsgi
    state: directory
    mode: 0755

- name: write uwsgi configuration
  template:
    src: templates/uwsgi.ini
    dest: /etc/uwsgi/nf_www.ini
  tags:
    deploy

- name: write supervisor configuration
  template:
    src: templates/supervisor.ini
    dest: /etc/supervisor/conf.d/nf_www.ini
  notify:
    - restart app process

  - name: restart uWSGI process
    supervisorctl:
      name: nf_www
      state: restarted
    become: yes
    tags:
      - deploy

- name: write nginx site configuration
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/conf.d/{{ app.name }}.conf
  become: yes
  notify:
    - reload nginx
  tags:
    deploy
